# kafka 服务部署
# https://github.com/wurstmeister/kafka-docker/blob/master/docker-compose-swarm.yml
version: '3.6'
services:
  zookeeper:
    image: zh-registry.geostar.com.cn/geopanel/zookeeper:3.6.2
    ports:
      - "2181:2181"
  kafka:
    image: zh-registry.geostar.com.cn/geopanel/kafka:2.12-2.5.0
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock